In [1]:
import os
import pandas as pd
import numpy as np
import shutil
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
from torchvision import transforms
import torch

In [2]:
x = torch.rand(1,1,4,4)

In [4]:
block_size = 2
num_blocks = (x.shape[-1] // block_size)**2
print(num_blocks)

4


In [6]:
print(x)
for i in range(0, x.shape[-1], block_size):
    for j in range(0, x.shape[-1], block_size):
        print(x[:, :, i:i+block_size, j:j+block_size])

tensor([[[[0.1157, 0.1381, 0.4287, 0.9686],
          [0.8617, 0.5661, 0.7504, 0.9481],
          [0.6765, 0.0781, 0.1254, 0.5907],
          [0.0200, 0.2357, 0.4185, 0.8004]]]])
tensor([[[[0.1157, 0.1381],
          [0.8617, 0.5661]]]])
tensor([[[[0.4287, 0.9686],
          [0.7504, 0.9481]]]])
tensor([[[[0.6765, 0.0781],
          [0.0200, 0.2357]]]])
tensor([[[[0.1254, 0.5907],
          [0.4185, 0.8004]]]])


In [2]:
import pandas as pd

df = pd.read_csv('data/celeba/identity_CelebA.txt', delimiter=' ', header = None, names = ['filename', 'class'])
print(df)

          filename  class
0       000001.jpg   2880
1       000002.jpg   2937
2       000003.jpg   8692
3       000004.jpg   5805
4       000005.jpg   9295
...            ...    ...
202594  202595.jpg   9761
202595  202596.jpg   7192
202596  202597.jpg   9852
202597  202598.jpg   5570
202598  202599.jpg  10101

[202599 rows x 2 columns]


In [3]:
class_names = list(np.unique(np.array(df['class'].to_list())))

In [4]:
len(class_names)

10177

In [5]:
len(df['class'].to_list())

202599

In [6]:
filename_list = df['filename'].to_list()

In [7]:
len(filename_list)

202599

In [8]:
folders_dict = dict()
for i in range(len(filename_list)):
    class_name = df['class'][i]
    if class_name not in folders_dict.keys():
        folders_dict[class_name] = [df['filename'][i]]
    else:
        folders_dict[class_name].append(df['filename'][i])

In [9]:
master_path = 'data/celeba/processed/'
source_path = 'data/celeba/img_align_celeba/'

In [10]:
for class_name in folders_dict.keys():
    class_name_str = str(class_name)
    os.mkdir(master_path + class_name_str + '/')
    for filename in folders_dict[class_name]:
        old_path = os.path.join(source_path, filename)
        new_path = os.path.join(master_path, class_name_str + '/')
        shutil.move(old_path, new_path)

In [2]:
IMAGE_PATH = 'data/celeba/processed/'
batch_size = 64
image_size = 64

In [3]:
transform = transforms.Compose([
    transforms.Resize(image_size),
    transforms.CenterCrop(image_size),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

dataset = ImageFolder(IMAGE_PATH, transform)
data_loader = DataLoader(dataset=dataset, batch_size=batch_size, shuffle=True, num_workers=8, drop_last=True)

In [4]:
img, labels = next(iter(data_loader))

In [5]:
img.shape

torch.Size([64, 3, 64, 64])